#!/usr/bin/python 
# SPDX-FileCopyrightText:2022 Akiya Wakaumi
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

if (ans %2 == 0):
    print("even number")
else:
    print("odd number")
